import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { AuthSessionProvider } from "@/context/AuthenticationProvider";

const inter = Inter({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "IQ Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
